### ISSUE TITLE
Cron runs twice at the set time

### ISSUE THREAD

**Issue by arsinawaz** [node-schedule/node-schedule#263]
I want to run it every 5 minute from 8-22. It runs two times every 5 minutes.

I am using node-schedule version 1.0.0 with node version 5.0.0.

```
  var schedule = require('node-schedule');
  var postman = schedule.scheduleJob('0 */5 8-22 * * *', postmanFunction);
```

Any help would be appreciated.

**Comment by santigimeno** [comment]
@arsinawaz It's working for me. Output when `postmanFunction` just prints the current date.
```
Thu Mar 03 2016 11:50:00 GMT+0100 (CET)
Thu Mar 03 2016 11:55:00 GMT+0100 (CET)
Thu Mar 03 2016 12:00:00 GMT+0100 (CET)
Thu Mar 03 2016 12:05:00 GMT+0100 (CET)
Thu Mar 03 2016 12:10:00 GMT+0100 (CET)
Thu Mar 03 2016 12:15:00 GMT+0100 (CET)
Thu Mar 03 2016 12:20:00 GMT+0100 (CET)
Thu Mar 03 2016 12:25:00 GMT+0100 (CET)
Thu Mar 03 2016 12:30:00 GMT+0100 (CET)
Thu Mar 03 2016 12:35:00 GMT+0100 (CET)
Thu Mar 03 2016 12:40:00 GMT+0100 (CET)
Thu Mar 03 2016 12:45:00 GMT+0100 (CET)
Thu Mar 03 2016 12:50:00 GMT+0100 (CET)
Thu Mar 03 2016 12:55:00 GMT+0100 (CET)
```

Can you be more specific on the issue you are observing and what would be your expected result? Thanks

**Comment by arsinawaz** [comment]
I am trying to send emails to users, and node schedule checks from backend if there are any emails to send every 5 minute from 8-22.

I even removed the emailing code and just placed a console.log of the current datatime. It prints the current datetime twice every 5 minutes. i have tried different timings to run the job but the same behaviour.

**Comment by arsinawaz** [comment]
i think problem is with my nodejs, it even executes setInterval twice but i am not able to find out why this happens :/

**Comment by codydaig** [comment]
I am having a similar issue where if my app is running for more than 24 hours, after the next midnight cycle, it will execute all scheduled commands 2 or 3 times. (Varies if it's 2 or 3). For now my fix is restarting the node process every night just after midnight before any scheduled events occur.

**Comment by santigimeno** [comment]
@codydaig Do you have a reproducible test case? Is your computer suspending some time? If that's the case see: https://github.com/node-schedule/node-schedule/issues/96

**Comment by codydaig** [comment]
The server is not suspending time. I've confirmed that it's the node-scheduler is firing each event twice. It seems to happen more frequently with the more events that get scheduled. 

Server Info:
Ubuntu 14.04
node v4.3.2
The latest version of the node-schedule package.

**Comment by santigimeno** [comment]
Without a reproducible test case it's going to be hard to find out what the issue might be. :/

**Comment by aberope** [comment]
Hello! finally I got this issue. I am experiencing the same problem. I am running scheduled jobs to send text over a chat and after 24 hours it launches between 1 and 2 times more than the unique.

Please fix this, I was trying to hunt this bug, thinking it was my fault and we need this module to run perfectly.

**Comment by albertdatui** [comment]
Hi,

Can you provide us with the test case that can generate the bug?
It will be very helpful.

Thanks

**Comment by santigimeno** [comment]
Sure, but without a reproducible test case it's going to be hard.

**Comment by aberope** [comment]
I need 1 day to reproduce the bug.

Basically following the example in github you setup a cron with my interval: 0 15 9 * * 1-5 to do a console.log('This is a message'), tomorrow should say once, but the day after tomorrow will be 1 or 2 more. That's all.

```  /**
   * installs crons from database
   * @param  {[type]} bot [description]
   * @return {[type]}     [description]
   */
  lib.setupCrons = function(bot) {
    lib.selectCrons(bot, null, function (rows, fields) {
      lib.cronjobs = []
      rows.forEach(function(row) {
        row.message = JSON.parse(row.message)
        var job = lib.schedule.scheduleJob(row.frequency, function(){
          lib.controller.receiveMessage(bot, row.message)
        })
        lib.cronjobs.push(job)
      })
      console.log('+ crons installed.')
    })
  }
```

this is executed twice or more:
```
function(){
          lib.controller.receiveMessage(bot, row.message)
        })
```

**Comment by santigimeno** [comment]
@aberope ok thanks. Can you try to reduce that to a standalone script we can run?

**Comment by aberope** [comment]
```
var cron = require('node-schedule')

cron.scheduleJob('0 15 9 * * 1-5', function() {
	console.log('It\'s ' + new Date() + '.')
})
```

this should say the time every day at 9:15 am. But if you run it on Monday, Wednesday should say it twice. Run with nohup and revise log every day.

I must say I have not experimented the bug with this code because I did for you and I need 2 days. But it's the same principle.

**Comment by santigimeno** [comment]
@aberope much better now, thanks :). Ok, I suppose you're using the latest `node-schedule` version, right?

**Comment by santigimeno** [comment]
Using `sinon` to fake the timers I can't reproduce the issue. Output of a simulation of 30 days starting from today:

```
Starting test on Thu Apr 21 2016 11:46:19 GMT+0200 (CEST)
It's Fri Apr 22 2016 09:15:00 GMT+0200 (CEST).
It's Mon Apr 25 2016 09:15:00 GMT+0200 (CEST).
It's Tue Apr 26 2016 09:15:00 GMT+0200 (CEST).
It's Wed Apr 27 2016 09:15:00 GMT+0200 (CEST).
It's Thu Apr 28 2016 09:15:00 GMT+0200 (CEST).
It's Fri Apr 29 2016 09:15:00 GMT+0200 (CEST).
It's Mon May 02 2016 09:15:00 GMT+0200 (CEST).
It's Tue May 03 2016 09:15:00 GMT+0200 (CEST).
It's Wed May 04 2016 09:15:00 GMT+0200 (CEST).
It's Thu May 05 2016 09:15:00 GMT+0200 (CEST).
It's Fri May 06 2016 09:15:00 GMT+0200 (CEST).
It's Mon May 09 2016 09:15:00 GMT+0200 (CEST).
It's Tue May 10 2016 09:15:00 GMT+0200 (CEST).
It's Wed May 11 2016 09:15:00 GMT+0200 (CEST).
It's Thu May 12 2016 09:15:00 GMT+0200 (CEST).
It's Fri May 13 2016 09:15:00 GMT+0200 (CEST).
It's Mon May 16 2016 09:15:00 GMT+0200 (CEST).
It's Tue May 17 2016 09:15:00 GMT+0200 (CEST).
It's Wed May 18 2016 09:15:00 GMT+0200 (CEST).
It's Thu May 19 2016 09:15:00 GMT+0200 (CEST).
It's Fri May 20 2016 09:15:00 GMT+0200 (CEST).
```

**Comment by aberope** [comment]
This is on my package.json:
    "node-schedule": "^1.1.0",

How can I fake timers to test it on my bugged version?

**Comment by santigimeno** [comment]
```
var cron = require('./');
var sinon = require('sinon');

var now = Date.now();

var clock = sinon.useFakeTimers();

clock.tick(now);

console.log('Starting test on ' + new Date());

cron.scheduleJob('0 15 9 * * 1-5', function() {
    console.log('It\'s ' + new Date() + '.')
});

clock.tick(30 * 24 * 60 * 60 * 1000);
```

**Comment by aberope** [comment]
I can not connect to the server due to the faked timers, if I comment sinon.useFakeTimers() it connects.

Anyway, seems as there's a background process and it's not affected by this fake, because in essence this is the bug. Next week I will now if it's a bug or my code because I changed the cron module.

Tell me what you need and I'll help.

**Comment by aberope** [comment]
Hello, why can't I force to launch the job without sinon, just with `date` command? I am trying to reproduce the bug, I can not recode the program to `node-schedule` again if continues bugged.

Please, think about what is running that can't be forced with fake timers because it happens when the time passes in the reality.

**Comment by aberope** [comment]
Hello,

this is just a message to motivate to fix this module. Not pretending to offend.

I changed to `cron` module from npmjs and the bug is not anymore.

The bug can't be reproduced with sinon and faketimers, you must wait for a whole day. So the fix should be shown by thinking in other way.

**Comment by aberope** [comment]
Well, now happened again with another module still twice. But I coded some logging routines and it's due to disconnect-reconnect it installs the crons again...

**Comment by santigimeno** [comment]
> But I coded some logging routines and it's due to disconnect-reconnect it installs the crons again...

@aberope what do you mean by that? Is there code scheduling the job for a second time?

**Comment by arsinawaz** [comment]
I was able to solve it, the problem was due to the multiple clusters node was running on. As in my case node was running on two clusters so it executed the job twice.
```
var cluster = require('cluster');
if(cluster.worker.id == 1){
 // run job
}
```

**Comment by santigimeno** [comment]
@arsinawaz That's great news!

**Comment by aberope** [comment]
Yeah, I was able to solve it by removing duplicate entries. Would be perfect to avoid or add param multiple con strings and functions with same.

**Comment by santigimeno** [comment]
@aberope 
> Would be perfect to avoid or add param multiple con strings and functions with same.

I'm sorry I don't really understand what you're trying to say, could you reword this a little? Thanks!

**Comment by aberope** [comment]
sorry.

I meant that would be useful if the module prevents from setting an identical cron job, without passing a param to true for example. To avoid this kind of errors, because seems very common.

**Comment by santigimeno** [comment]
Ok, so the problem is when trying to schedule multiple jobs with the same name. The older jobs are not cancelled and not referenced in `scheduledJobs` anymore, right?

**Comment by aberope** [comment]
That maybe is a problem. What I suggest is to don't let programmer create jobs that are already launched if not passing a boolean variable.

**Comment by codydaig** [comment]
I was running the script on a VPS, but as soon as I moved it to a dedicated server it works. So, I almost wonder if it isn't an issue with the module as an issue with node and time tracking. When on the VPS, my work around was to restart the process every morning before any scheduled events ran.

**Comment by iericallen** [comment]
We also came across this bug. We were using 3 separate `schedule.RecurrenceRule()`'s to cover all 7 days of the week and send emails at different times. Over the course of a month, we didn't realize that each Sunday the cron was being fired off twice. 
![screen shot 2016-12-06 at 8 16 02 am](https://cloud.githubusercontent.com/assets/3165745/20930864/4e8988ce-bb8c-11e6-9d11-6d6cd9271f22.png)

[Click here]( https://gist.github.com/iericallen/9b04361927ff19b9ae281be81247cd31) to view the code where the bug exists, with tests to reproduce duplicates.  

[Click here](https://gist.github.com/iericallen/660e1325def134c31f35489226d1603f) to view the workaround code, with tests to show no duplicates.

**Comment by santigimeno** [comment]
@iericallen thanks for taking the time and post code that reproduces the issue. I'll try to take a look at it soon

**Comment by santigimeno** [comment]
@iericallen I've found the issue with your code. The problem is how `rule.dayOfWeek` is defined for every job. Let's go rule by rule:

```
rule.dayOfWeek = [0, new schedule.Range(6, 7)]; // sat/sun
```
This is equivalent as doing
```
rule.dayOfWeek = [0, 6, 7]; 
```
And taking into account that the valid range for `dayOfWeek` is `[0 - 6] === [Sunday - Saturday]` (yes, I know it's not documented anywhere), the rule is translated as **Sunday** and **Saturday**. So far so good.

Next rule:
```
rule.dayOfWeek = [0, new schedule.Range(1, 3)]; // M,T,W
```
This is equivalent as doing
```
rule.dayOfWeek = [0, 1, 2, 3]; 
```
Which translates as **Sunday**, **Monday**, **Tuesday** and **Wednesday**

Finally:
```
rule.dayOfWeek = [0, new schedule.Range(4, 5)]; // Th,F
```
This is equivalent as doing
```
rule.dayOfWeek = [0, 4, 5]; 
```
Which translates as **Sunday**, **Thursday** and **Friday**

Which count as 9 instead of the desired 7.

I hope things are clear now :)

P.S. I know the documentation is far (very far) from complete. PR improving the documentation are always welcome

**Comment by santigimeno** [comment]
@iericallen is this still an issue?

**Comment by ralphievolt** [comment]
`rule.dayOfWeek = [0, new schedule.Range(4, 5)];`   to `rule.dayOfWeek = [0, 4, 5];`

does this apply to hour, minutes, and seconds as weel?

**Comment by santigimeno** [comment]
> does this apply to hour, minutes, and seconds as well?

Yes.

> likerule.hour = [0, new schedule.Range(17, 20)]; to rule.hour = [0, 17, 20];

That's not correct. It should be:

`rule.hour = [0, 17, 18, 19, 20];`

**Comment by jonathan-nielsen** [comment]
I'm having this issue now.
The following code run twice:
```
(function loader() {
	const rule = new schedule.RecurrenceRule();
	rule.hour = 0;
	rule.minute = 30;

	schedule.scheduleJob(rule, () => {
		console.log(new Date(), 'Loading...');
		loadSomething();
	});
})();
```
This results in executions at: `2017-10-03T22:29:59.875Z` and `2017-10-03T22:30:00.006Z`.

This code works though:
```
(function builder() {
	const rule = new schedule.RecurrenceRule();
	rule.hour = 1;
	rule.minute = 0;

	schedule.scheduleJob(rule, () => {
		console.log(new Date(), 'Building...');
		buildSomething();
	});
})();
```
It was executed once at `2017-10-03T23:00:00.005Z`.

**Comment by Chronicless** [comment]
I have the same issue. Job runs 3 times in the same time (difference only in miliseconds)

**Comment by davidnjohnson** [comment]
I'm having this issue intermittently with 1.2.5.  When I set up a minute-based recurrence rule, it will occasionally trigger the rule multiple times.  There's only one job scheduled, and no clusters are involved.

Here's test code.  Note the counter:
```
var ticketSyncRule = new schedule.RecurrenceRule();
ticketSyncRule.minute = new schedule.Range(0, 59, 1);
var counter = 0;
var ticketSyncJob = schedule.scheduleJob('ticketSync', ticketSyncRule, function () {
  counter++;
  logger.info('ticketSyncJob triggered: ' + counter);
});
logger.info('job ' + ticketSyncJob.name + ' created: ' + counter);
```
And here's what happens:

> 2017-10-25T17:11:00.010Z - info: ticketSyncJob triggered: 1
> 2017-10-25T17:12:00.005Z - info: ticketSyncJob triggered: 2
> 2017-10-25T17:13:00.003Z - info: ticketSyncJob triggered: 3
> 2017-10-25T17:14:00.006Z - info: ticketSyncJob triggered: 4
> 2017-10-25T17:15:00.002Z - info: ticketSyncJob triggered: 5
> 2017-10-25T17:16:00.001Z - info: ticketSyncJob triggered: 6
> 2017-10-25T17:17:00.006Z - info: ticketSyncJob triggered: 7
> 2017-10-25T17:18:00.001Z - info: ticketSyncJob triggered: 8
> 2017-10-25T17:19:00.003Z - info: ticketSyncJob triggered: 9
> 2017-10-25T17:19:59.902Z - info: ticketSyncJob triggered: 10
> 2017-10-25T17:20:00.002Z - info: ticketSyncJob triggered: 11
> 2017-10-25T17:20:59.797Z - info: ticketSyncJob triggered: 12
> 2017-10-25T17:21:00.001Z - info: ticketSyncJob triggered: 13
> 2017-10-25T17:21:59.797Z - info: ticketSyncJob triggered: 14
> 2017-10-25T17:22:00.001Z - info: ticketSyncJob triggered: 15
> 2017-10-25T17:22:59.797Z - info: ticketSyncJob triggered: 16
> 2017-10-25T17:23:00.000Z - info: ticketSyncJob triggered: 17
> 2017-10-25T17:23:59.798Z - info: ticketSyncJob triggered: 18
> 2017-10-25T17:24:00.000Z - info: ticketSyncJob triggered: 19

Some kind of rounding problem, maybe?  Or just that the job not  being marked as triggered the next time the scheduler checks?

**Comment by santigimeno** [comment]
@davidnjohnson thanks for the report. Indeed it seems there's a bug. I'll try to look into it.

**Comment by santigimeno** [comment]
@davidnjohnson @jonathan-nielsen can you check if https://github.com/node-schedule/node-schedule/pull/396 fixes the issue for you?

**Comment by rsalunga29** [comment]
I am experiencing this issue, it calls my function twice or thrice (it varies). Are there any fix for this? I have the latest version of node and node-schedule

code:
`schedule.scheduleJob("40 * * * *", function(){
  test_function();
});`

**Comment by santigimeno** [comment]
@rsalunga29 can you check if https://github.com/node-schedule/node-schedule/pull/396 fixes the issue? Thanks

**Comment by thechile** [comment]
I have same issue. #396 does not fix it. I am using npm v1.3.0. 

e.g.

```
schedule.scheduleJob("* * * * * *", function(){ test_every_second_function(); });
schedule.scheduleJob("*/10 * * * * *", function(){ test_every_10_seconds_function(); });
```

It runs both jobs twice so `test_every_second_function` and `test_every_10_seconds_function` get run twice per second and twice every 10 seconds respectively.

**Comment by santigimeno** [comment]
I've been trying to reproduce the issue without success :(. On what OS are you having the issue?

**Comment by davidnjohnson** [comment]
Seems fixed for me.  Thanks.

**Comment by karsens** [comment]
I ended up here because I was worried about having a scheduled function execute 8 times when I run my node app in cluster mode on 8 cores. I couldn't find much about it, so I'll just ask... Is this a problem, or does this never happen? It's not addressed in the readme.

**Comment by mariohmol** [comment]
I cant have this working as well.. in 1.3.0. An this is running for every second.

I'm on mac but it happens on linux as well

```
schedule.scheduleJob('* */1 * * * * *', function () {
      console.log('Initial schedule for eventSendHours!');
```

**Comment by MewingPlane** [comment]
`_.forEach(scheduledJobcard, function(value,prop,item)
    {
        if (self.jobs[prop])
        {
            self.jobs[prop].cancel();
            delete self.jobs[prop];
        }

        self.jobs[prop] = schedule.scheduleJob(prop, function()
        {
            self.logger.debug(self.type+":"+arguments.callee.name,__line,"Schedule Begin ",prop);

        });

    });`

After a couple of weeks this issue with the scheduler can spawn up to 10 to 20 running at the same time. this is on the latest 1.3.2
I have tried downgrading with no luck. 
Tested this on Win7, Windows 10 

These are my logs after an hour 
14:59:00.007, EMSG=Schedule Begin  59 * * * *
14:59:06.268, EMSG=Schedule Begin  59 * * * *

**Comment by maciejpk** [comment]
I just ran into this issue by leaving the `node` program running in tmux session on `node-schedule` version `1.3.2`.

I can't really tell you how to reproduce this, but I want to assure you that this problem is still present. All I can tell you is that I left the program running for around 20 hours when bug appeared - every consecutive cronjob was run twice. Restarting the server fixed it

cronjob template: `*/60 * * * *`
node: `12.13.1`
node-schedule: `1.3.2`
AWS Lightsail instance, Debian 9

**Comment by manishrana87** [comment]
My job is running multiple times for this cron expression (0 31 13 ? * * *). It supposed to run once on a daily basis but it is not. It is running multiple time

schedule.scheduleJob(cronExpression, { tz: 'Asia/Kolkata' }, async () => {
      console.log("Inside schedule job");
    });

To generate the Cron expression I am using @sbzen/re-cron widget.

Can anyone help me with this?

**Comment by NgocSon159** [comment]
> I was able to solve it, the problem was due to the multiple clusters node was running on. As in my case node was running on two clusters so it executed the job twice.
> 
> ```
> var cluster = require('cluster');
> if(cluster.worker.id == 1){
>  // run job
> }
> ```

Thanks you so muchhhhh.

**Comment by NareshKukreti12** [comment]
@santigimeno   I am having the same issue . Though the cron is running once in the localhost and dev server. But on the production server it is executing twice  here is my code .
var job2 = new CronJob('00 00 10 * * *', async(res) => { await woStatusCheck(); }, null, false, 'Asia/Kolkata'); job2.start();

**Comment by ArunkumarRK** [comment]
> I was able to solve it, the problem was due to the multiple clusters node was running on. As in my case node was running on two clusters so it executed the job twice.
> 
> ```
> var cluster = require('cluster');
> if(cluster.worker.id == 1){
>  // run job
> }
> ```

It's very useful to resolve issues related to node-schedule on all the cores. Thanks do well.
